import { Button } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Some Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='grid place-items-center h-screen'>
        <h1 className='text-3xl font-semibold'>
          Welcome to Eat Honeybadgers!
        </h1>
        <Button variant='contained' onClick={() => router.push('/order')}>Begin your order</Button>
      </main>
    </div>
  )
}
